config/routes.rb
Rails.application.routes.draw do
  resources :configrations
  resources :recommend_articles
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:index, :show, :edit, :update] do 
    member do
      get :role_edit
      patch :role_update
    end
  end

  resources :genres do
    member do
      get :articles
    end
  end
  root 'articles#index'
  get 'articles/search', to: 'articles/search#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :articles
  has_many :genre_recommend_tags, dependent: :destroy
  accepts_nested_attributes_for :genre_recommend_tags, allow_destroy: true
  has_one_attached :image #active_starage
  has_one_attached :icon #active_starage
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_genre, only: [:show, :edit, :show, :update, :destroy]
  before_action :is_admin, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def index
    @genres = Genre.all.order(order_number: :asc)
  end

  def articles
    order = 'id desc'
    if params[:order].present? && params[:order].to_s == "pv"
      order = 'pv_count desc'
    end
    @genre = Genre.find params[:id]
    @articles = @genre.articles
                      .where(release: true)
                      .order(order)
                      .page(params[:page])
                      .per(20)
    @ranking_articles = Article.where(genre_id: @genre.id)
                               .where(release: true)
                               .order(pv_count: :desc)
                               .limit(5)
                               .offset(0)
    render 'articles/index'
  end

  def show
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end

    def genre_params
      params.require(:genre)
            .permit(:title,
                    :text,
                    :order_number,
                    :image,
                    :icon,
                    genre_recommend_tags_attributes: [
                      :title,
                      :id,
                      :_destroy],)
    end

    def is_admin
      if current_user.role != 'admin'
        redirect_to root_path and return
      end
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
= form_for @genre do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@genre.errors.count, "error")} prohibited this genre from being saved:"
      %ul
        - @genre.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :order_number
    = f.number_field :order_number
  .field
    = f.label "トップ画像"
    = f.file_field :image,
                    id: 'previw',
                    onchange: "previewFile('previw')",
                    accept: 'image/*'
    - if @genre.image.present?
      = image_tag @genre.image.variant(resize_to_fit: [200, 200])
    - else
      = image_tag '', name: "previw"
  .field
    = f.label "アイコン"
    = f.file_field :icon,
                    id: 'previw',
                    onchange: "previewFile('icon')",
                    accept: 'image/*'
    - if @genre.icon.present?
      = image_tag @genre.icon.variant(resize_to_fit: [20, 20])
    - else
      = image_tag '', name: "icon"
  #tags.my-2
    %p
      タグ
    = f.nested_fields :genre_recommend_tags do |tag|
      .field
        = tag.text_field :title
        = tag.remove_nested_fields_button '削除'
    = f.add_nested_fields_button :genre_recommend_tags, '追加'
  .actions
    = f.submit 'Save'

app/views/genres/edit.html.haml
%h1 Editing genre

= render 'form'

= link_to 'Show', @genre
\|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
%h1 Listing genres

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @genres.each do |genre|
      %tr
        %td= genre.title
        %td= link_to 'Show', genre
        %td= link_to 'Edit', edit_genre_path(genre)
        %td= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Genre', new_genre_path

app/views/genres/new.html.haml
%h1 New genre

= render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @genre.title
%p
  %b text:
  = @genre.text
.image
  - if @genre.image.present?
    = image_tag @genre.image.variant(resize_to_fit: [200, 200])
= link_to 'Edit', edit_genre_path(@genre)
\|
= link_to 'Back', genres_path