config/routes.rb
Rails.application.routes.draw do
  resources :configrations
  resources :recommend_articles
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:index, :show, :edit, :update] do 
    member do
      get :role_edit
      patch :role_update
    end
  end

  resources :genres do
    member do
      get :articles
    end
  end
  root 'articles#index'
  get 'articles/search', to: 'articles/search#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  belongs_to :genre
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true
  has_one_attached :image #active_starage
  has_many :recommend_articles

  is_impressionable :counter_cache => true, :column_name => :pv_count, unique: :all

  validates :title, presence: true

  scope :tags_search, ->(tags, titles) {
    if tags.present? || titles.present?
      where(id: tags).or(where(id: titles))
    end
  }

  extend OrderAsSpecified #gem extend OrderAsSpecified で並び替えする為の記述
end

app/controllers/articles/search_controller.rb
class Articles::SearchController < ApplicationController
  def index
    #オーだー
    order = 'id desc'
    if params[:order].present? && params[:order].to_s == "pv"
      order = 'pv_count desc'
    end
    #検索処理
    @search_params = ""
    if params[:keyword].present?
      @search_params = params[:keyword].to_s
      sp = params[:keyword].gsub("　"," ")#全角スペースを半角スペースに変換
      sp.chop! if sp[sp.length-1] == " "#最後の文字がスペースだったら削除
      sp = sp.gsub(" ","%,%")#半角スペースをカンマに変換(プレスホルダーの第二引数以降に使用する変数spに代入)
      sp = '%'+sp+'%'
      sp = sp.split(",")#ひとつの文字列だったspをカンマで区切って配列にする

      eventTags = Array.new
      eventTitles = Array.new
      eventOwners = Array.new

      sp.each.with_index do |keyword, i|
        if i > 0
          eventTags = eventTags & Tag.where('title like ?', keyword).pluck(:article_id)
          eventTitles = Article.where('title like ?', keyword).pluck(:id)
        else
          eventTags.push(*Tag.where('title like ?', keyword).pluck(:article_id))
          eventTitles.push(*Article.where('title like ?', keyword).pluck(:id))
        end
      end

      if eventTags.present? || eventTitles.present?
        @articles = Article.where(release: true)
                        .tags_search(eventTags, eventTitles)#scope
                        .order(order)
                        .distinct
                        .page(params[:page])
                        .per(20)
        #検索結果に表示にするタグ一覧ほインスタンス変数に保存
        @searchTags = params[:keyword].gsub("　"," ")
      else
        @articles = Article.none
                        .page(params[:page])
                        .per(20)
      end
    else
      redirect_back(fallback_location: root_path) and return
    end

    @ranking_articles = Article.where(release: true)
                       .order(pv_count: :desc)
                       .limit(5)
                       .offset(0)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :can_edit, only: [:edit, :update, :duplication, :destroy]
  before_action :unless_user, only: [:new, :create]

  def index
    # raise.params.inspect
    order = 'id desc'
    if params[:order].present? && params[:order].to_s == "pv"
      order = 'pv_count desc'
    end
    @articles = Article.where(release: true)
                       .order(order)
                       .page(params[:page])
                       .per(20)
    @ranking_articles = Article.where(release: true)
                       .order(pv_count: :desc)
                       .limit(5)
                       .offset(0)
  end

  def show
    unless @article.release
      if user_signed_in?
        can_edit
      else
        redirect_to root_path and return
      end
    end

    @ranking_articles = Article.where(release: true)
                               .where(genre_id: @article.genre.id)
                               .order(pv_count: :desc)
                               .limit(5)
                               .offset(0)
    #アクセス数
    begin
      impressionist(@article, nil, unique: [:session_hash])
    rescue
    end

    each_count = 0
    ph_tag = ""
    tags = Array.new
    @article.tags.each do |tag|
      tags.push(tag.title)
      if each_count > 0
        ph_tag += " OR "
      end
      ph_tag += "tags.title like ?"
      each_count += 1
    end
    #表示する記事と同じタグが付いてる動画を一致するタグが多い順にIDを配列で格納
    relatedArticle_count = Article.joins(:tags)
      .where("#{ph_tag}", *tags)
      .group(:id)
      .order('count_id desc')
      .limit(5)
      .offset(0)
      .count(:id).keys
    #関連動画一覧のID一覧配列から表示する動画のIDを削除
    relatedArticle_count.each do |rvc|
      if rvc == params[:id].to_i
        relatedArticle_count.delete(rvc)
      end
    end
    #上で作った一致タグが多い順のID配列でwhereして並び替え
    @relateArticles = Article.where(id: relatedArticle_count)
                              .order_as_specified(id: relatedArticle_count)

    respond_to do |format|
      format.html { render :show }
      format.json { render :show }
    end
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # raise.params.inspect
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def can_edit
      if @article.user_id != current_user.id &&
      current_user.role != 'contributor' &&
      current_user.role != 'editor' &&
      current_user.role != 'admin'
        redirect_to root_path and return
      end
    end

    def unless_user
      if current_user.role == 'user'
        redirect_to root_path and return
      end
    end

    def article_params
      params.require(:article)
            .permit(
              :title,
              :eyecatch,
              :content,
              :genre_id,
              :image,
              :release,
              tags_attributes: [
                :title,
                :id,
                :_destroy],)
    end
end

app/helpers/articles/search_helper.rb
module Articles::SearchHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.haml
%ul.articles
  - @articles.each do |article|
    %li
      = link_to article do
        - if article.image.present?
          = image_tag article.image.variant(resize_to_fit: [200, 200])
        - else
          %img{:src => "http://placehold.it/100x100"}/
        .text_area
          %p.title=article.title
          %p.text=truncate(article.eyecatch, length: 100)

app/views/articles/_form.html.haml
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label 'タイトル'
    = form.text_field :title, class: 'title'
  .field
    = form.label 'アイキャッチ'
    = form.text_area :eyecatch, class: 'text'
  .field
    = form.label :genre_id do
      ジャンル
      %span.required
        (必須)
    = form.collection_select :genre_id,
                          Genre.all.order(id: :asc),
                          :id, :title, {}, {class: 'genre'}
  .field
    = form.label '画像'
    = form.file_field :image,
                    id: 'previw',
                    onchange: "previewFile('previw')",
                    accept: 'image/*'
    - if controller_name == 'articles' && (action_name == 'new' || action_name == 'create')
      = image_tag '', name: "previw"
    - else
      - if @article.image.present?
        = image_tag @article.image.variant(resize_to_fit: [600, 600]), name: "previw"
      - else
        = image_tag '', name: "previw"

  #tags.my-2
    %p
      タグ
    = form.nested_fields :tags do |tag|
      .field
        = tag.text_field :title
        = tag.remove_nested_fields_button '削除'
    = form.add_nested_fields_button :tags, '追加'
  .field
    = form.label '公開する'
    = form.check_box :release, { class: 'checker_class_mp'}, 'true', 'false'
  .field.mt-ios
    = form.rich_text_area :content
  .actions
    = form.submit

app/views/articles/_right_sidebar.html.haml
.right_sidebar
  .article_ranking
    .title_section
      - if controller_name == 'genres' && action_name == 'articles'
        %h4="#{@genre.title}のランキング"
        %p="人気の#{@genre.title}の記事"
      - elsif controller_name == 'articles' && action_name == 'show'
        %h4="#{@article.genre.title}のランキング"
        %p="人気の#{@article.genre.title}の記事"
      - else
        %h4="ランキング"
        %p="人気の記事"
    %ul.articles
      - @ranking_articles.each.with_index(1) do |article, i|
        %li
          = link_to article do
            .img_area
              %p.ranking_number="#{i.to_s}"
              - if article.image.present?
                = image_tag article.image.variant(resize_to_fit: [200, 200])
              - else
                %img{:src => "http://placehold.it/50x50"}/
            .text_area
              %p.title=article.title
  .recommend_articles
    .title_section
      %h4 おすすめ記事
      %p 当サイト管理人からのおすすめ記事です！
    %ul.articles
      - RecommendArticle.all.order(order_number: :asc).each.with_index(1) do |article, i|
        %li
          = link_to article.article do
            .img_area
              - if article.article.image.present?
                = image_tag article.article.image.variant(resize_to_fit: [200, 200])
              - else
                %img{:src => "http://placehold.it/50x50"}/
            .text_area
              %p.title=article.article.title
  -#
    .author_ranking
      .title_section
        %h4 人気のライター
        %p ファッションで人気のライター
      %ul.authors
        %li
          %a{:href => "#"}
            %img{:src => "http://placehold.it/75x75"}/
            .text_area
              %p.name 山田 太郎
              %p.profile 素敵な旅をお届けします
        %li
          %a{:href => "#"}
            %img{:src => "http://placehold.it/75x75"}/
            .text_area
              %p.name 山田 太郎
              %p.profile 素敵な旅をお届けします
        %li
          %a{:href => "#"}
            %img{:src => "http://placehold.it/75x75"}/
            .text_area
              %p.name 山田 太郎
              %p.profile 素敵な旅をお届けします

app/views/articles/edit.html.haml
.article_edit
  = render 'form', article: @article

app/views/articles/index.html.haml
.eyecatch
  .eyecatch_inner
    - configration = Configration.all.first
    - if controller_name == 'genres' && action_name == 'articles'
      - if @genre.image.present?
        = image_tag @genre.image.variant(resize_to_fit: [300, 300])
      - else
        %img{:src => "http://placehold.it/200x200"}/
    - else
      - if configration.sitelogo.present?
        = image_tag configration.sitelogo
    - if controller_name == 'genres' && action_name == 'articles'
      .text_area
        %p.title=@genre.title
        %p.text=@genre.text
        %ul.tags
          - @genre.genre_recommend_tags.each do |tag|
            %li.tag
              = link_to tag.title, articles_search_path(keyword: tag.title)
    - else
      .text_area
        %p.title ホーム
        %p.text= configration.eyecatch
.contents
  .left_sidebar
    %h5 記事
    %ul.categories
      - if controller_name == 'articles' && action_name == 'index'
        - active = true
      - else
        - active = false
      %li{ class: "#{active ? 'active' : ''}"}
        = link_to root_path do
          %img{:src => "http://placehold.it/20x20"}>/
          ホーム
      - Genre.all.order(order_number: :asc).each do |genre|
        - if controller_name == 'genres' && action_name == 'articles' && @genre.id == genre.id
          - active = true
        - else
          - active = false
        %li{ class: "#{active ? 'active' : ''}"}
          = link_to articles_genre_path(genre.id) do
            - if genre.icon.present?
              = image_tag genre.icon.variant(resize_to_fit: [20, 20])
            - else
              %img{:src => "http://placehold.it/20x20"}>/
            = genre.title
  .articles_area
    - if controller_name == 'genres' && action_name == 'articles'
      %h4="#{@genre.title}の記事一覧"
    - else 
      %h4="記事一覧"
    .order_change_area
      - if /order=pv/ =~ request.url
        = link_to '新着', "#{request.path_info}"
        %p.active{:href => "#"} 人気順
      - else
        %p.active{:href => "#"} 新着
        = link_to '人気順', "#{request.path_info}?order=pv"
    = render 'articles/articles'
    .paginate
      .page_entries_info
        = page_entries_info @articles
      .pagination
        = paginate @articles
  = render 'articles/right_sidebar'

app/views/articles/new.html.haml
%h1 新規記事登録
.article_new
  = render 'form', article: @article

app/views/articles/show.html.haml
- content_for :title do
  = @article.title + ' | ねこの怪奇ファイル'
.contents.show
  .articles_area
    .title_area
      %h1=@article.title
      %p.text=@article.eyecatch
      %ul.tags
        - @article.tags.each do |tag|
          %li.tag
            = link_to tag.title, articles_search_path(keyword: tag.title)
      .count_area
        %p.count_text
          %span.count=@article.pv_count
          View
      - if @article.image.present?
        = image_tag @article.image.variant(resize_to_fit: [600, 600])
    - if user_signed_in? && |
         (@article.user_id == current_user.id || |
         current_user.role == 'contributor' || |
         current_user.role == 'editor' || |
         current_user.role == 'admin') |
      = link_to 'Edit', edit_article_path(@article)
      = link_to 'Destroy', article_path, method: :delete, data: { confirm: 'Are you sure?' }
    .article
      = raw CGI.unescape_element @article.content.to_s, ['iframe', 'blockquote', 'p', 'a']
      -# = @article.content
    .related_post
      %h4 関連する記事
      %ul.articles
        - @relateArticles.each do |article|
          %li
            = link_to article do
              - if article.image.present?
                = image_tag article.image.variant(resize_to_fit: [150, 150])
              - else
                %img{:src => "http://placehold.it/100x100"}/
              .text_area
                %p.title= article.title
                %p.text= truncate(article.eyecatch, length: 100)
  = render 'right_sidebar'
%script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}