config/routes.rb
Rails.application.routes.draw do
  resources :configrations
  resources :recommend_articles
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:index, :show, :edit, :update] do 
    member do
      get :role_edit
      patch :role_update
    end
  end

  resources :genres do
    member do
      get :articles
    end
  end
  root 'articles#index'
  get 'articles/search', to: 'articles/search#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/configration.rb
class Configration < ApplicationRecord
  has_one_attached :sitelogo #active_starage
  has_one_attached :home_icon #active_starage
end

app/controllers/configrations_controller.rb
class ConfigrationsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_configration, only: [:show, :edit, :update, :destroy]
  before_action :is_admin, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def index
    @configrations = Configration.all
  end

  def show
  end

  def new
    @configration = Configration.new
  end

  def edit
  end

  def create
    @configration = Configration.new(configration_params)

    respond_to do |format|
      if @configration.save
        format.html { redirect_to @configration, notice: 'Configration was successfully created.' }
        format.json { render :show, status: :created, location: @configration }
      else
        format.html { render :new }
        format.json { render json: @configration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @configration.update(configration_params)
        format.html { redirect_to @configration, notice: 'Configration was successfully updated.' }
        format.json { render :show, status: :ok, location: @configration }
      else
        format.html { render :edit }
        format.json { render json: @configration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @configration.destroy
    respond_to do |format|
      format.html { redirect_to configrations_url, notice: 'Configration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_configration
      @configration = Configration.find(params[:id])
    end

    def configration_params
      params.require(:configration).permit(:eyecatch, :sitelogo, :home_icon)
    end

    def is_admin
      if current_user.role != 'admin'
        redirect_to root_path and return
      end
    end
end

app/helpers/configrations_helper.rb
module ConfigrationsHelper
end

app/views/configrations/_form.html.haml
= form_for @configration do |f|
  - if @configration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@configration.errors.count, "error")} prohibited this configration from being saved:"
      %ul
        - @configration.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :eyecatch
    = f.text_area :eyecatch
  .field
    = f.label "サイトロゴ"
    = f.file_field :sitelogo,
                    id: 'previw',
                    accept: 'image/*'
  .field
    = f.label "ホームアイコン"
    = f.file_field :home_icon,
                    id: 'previw',
                    accept: 'image/*'
  .actions
    = f.submit 'Save'

app/views/configrations/edit.html.haml
%h1 Editing configration

= render 'form'

= link_to 'Show', @configration
\|
= link_to 'Back', configrations_path

app/views/configrations/index.html.haml
%h1 Listing configrations

%table
  %thead
    %tr
      %th Eyecatch
      %th
      %th
      %th

  %tbody
    - @configrations.each do |configration|
      %tr
        %td= configration.eyecatch
        %td= link_to 'Show', configration
        %td= link_to 'Edit', edit_configration_path(configration)
        %td= link_to 'Destroy', configration, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Configration', new_configration_path

app/views/configrations/new.html.haml
%h1 New configration

= render 'form'

= link_to 'Back', configrations_path

app/views/configrations/show.html.haml
%p#notice= notice

%p
  %b Eyecatch:
  = @configration.eyecatch
.image
  - if @configration.sitelogo.present?
    = image_tag @configration.sitelogo.variant(resize_to_fit: [200, 200])
.image
  - if @configration.home_icon.present?
    = image_tag @configration.home_icon.variant(resize_to_fit: [20, 20])
= link_to 'Edit', edit_configration_path(@configration)
\|
= link_to 'Back', configrations_path