config/routes.rb
Rails.application.routes.draw do
  resources :configrations
  resources :recommend_articles
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    sessions: "users/sessions",
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, :only => [:index, :show, :edit, :update] do 
    member do
      get :role_edit
      patch :role_update
    end
  end

  resources :genres do
    member do
      get :articles
    end
  end
  root 'articles#index'
  get 'articles/search', to: 'articles/search#index'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "description", content: "世界の驚愕の事実を掲載していくサービス！" }
    %meta{name: "keywords", content: "ミステリー,怪奇,陰謀,権力争い"}
    - title = content_for?(:title) ? yield(:title) : 'ねこの怪奇ファイル'
    %title
      = title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application'
    %link{:href => "/apple-touch-icon.png", :rel => "apple-touch-icon", :sizes => "180x180"}/
    %link{:href => "/favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
    %link{:href => "/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %link{:href => "/site.webmanifest", :rel => "manifest"}/
    %link{:color => "#5bbad5", :href => "/safari-pinned-tab.svg", :rel => "mask-icon"}/
    %meta{:content => "#da532c", :name => "msapplication-TileColor"}/
    %meta{:content => "#ffffff", :name => "theme-color"}/
    - if controller.controller_name == 'articles' && controller.action_name == 'show'
      %meta{:content => "#{@article.title}", :property => "og:title"}/
      %meta{:content => "article", :property => "og:type"}/
      %meta{:content => "#{@article.eyecatch}", :property => "og:description"}/
      %meta{:content => "#{request.url}", :property => "og:url"}/
      - if @article.image.present?
        %meta{:content => "#{rails_representation_url(@article.image.variant(resize_to_limit: [300, 300], strip: true).processed, disposition: :inline)}", :property => "og:image"}/
    - else
      %meta{:content => "ねこの怪奇ファイル", :property => "og:title"}/
      %meta{:content => "website", :property => "og:type"}/
      %meta{:content => "世界の驚愕の事実を掲載していくサービス！", :property => "og:description"}/
      %meta{:content => "#{request.url}", :property => "og:url"}/
    - if /nekokai.net/ =~ request.url
      /Google Analytics
      %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=G-DZERLD88C8"}
      :javascript
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-DZERLD88C8');
  %body
    %nav.navbar_lg
      - search_params = ""
      - if @search_params.present?
        - search_params = @search_params
      .search_form
        = form_with(url: articles_search_path, local: true, method: :get, class: 'form') do |f|
          = f.text_field :keyword, value: search_params, class: 'search_text', placeholder: '気になるワードを入力'
          %input.search_button{:type => "submit", :value => ""}/
      = link_to root_path do
        = image_tag 'nekokailogo.png'
      .link_area
        - if user_signed_in?
          - if current_user.role != 'user'
            = link_to '新規登録', new_article_path
            - if current_user.role == 'admin' || |
                 current_user.role == 'editor' |
              = link_to 'おすすめ', recommend_articles_path
            = link_to 'マイページ', user_path(current_user.id)
          = link_to 'プロフィール変更', edit_user_path(current_user.id)
          = link_to ' ログアウト', destroy_user_session_path, method: :delete
        - else
          = link_to 'ログイン', new_user_session_path
    .navbar.navbar_min
      .logo_area
        = link_to root_path do
          = image_tag 'nekokailogo.png'
      %nav#min_navbar.global-nav
        %ul.global-nav__list.categories
          - if user_signed_in?
            - if current_user.role != 'user'
              %li= link_to '新規登録', new_article_path
              - if current_user.role == 'admin' || |
                  current_user.role == 'editor' |
                %li= link_to 'おすすめ', recommend_articles_path
              %li= link_to 'マイページ', user_path(current_user.id)
            %li= link_to 'プロフィール変更', edit_user_path(current_user.id)
            %li= link_to ' ログアウト', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'ログイン', new_user_session_path
          - if controller_name == 'articles' && action_name == 'index'
            - active = true
          - else
            - active = false
          .search_form
            = form_with(url: articles_search_path, local: true, method: :get, class: 'form') do |f|
              = f.text_field :keyword, value: search_params, class: 'search_text', placeholder: '気になるワードを入力'
              %input.search_button{:type => "submit", :value => ""}/
          %li{ class: "#{active ? 'active' : ''}"}
            = link_to root_path do
              %img{:src => "http://placehold.it/20x20"}>/
              ホーム
          - Genre.all.order(order_number: :asc).each do |genre|
            - if controller_name == 'genres' && action_name == 'articles' && @genre.id == genre.id
              - active = true
            - else
              - active = false
            %li{ class: "#{active ? 'active' : ''}"}
              = link_to articles_genre_path(genre.id) do
                - if genre.icon.present?
                  = image_tag genre.icon.variant(resize_to_fit: [20, 20])
                - else
                  %img{:src => "http://placehold.it/20x20"}>/
                = genre.title
      #js-hamburger.hamburger
        %span.hamburger__line.hamburger__line--1
        %span.hamburger__line.hamburger__line--2
        %span.hamburger__line.hamburger__line--3
      #js-black-bg.black-bg
    .container
      = yield
    %footer
      %p.copyright Copyright © 2020-2021 ○○○○ All Rights Reserved.
      %p 当サイト内の文章・画像等の無断転載及び複製等の行為は禁じます。

:javascript
  function toggleNav() {
    var body = document.body;
    var hamburger = document.getElementById('js-hamburger');
    var blackBg = document.getElementById('js-black-bg');

    hamburger.addEventListener('click', function() {
      body.classList.toggle('nav-open');
    });
    blackBg.addEventListener('click', function() {
      body.classList.remove('nav-open');
    });
  }
  toggleNav();